### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by noncodo** [sarahmid/nofold#2]
I'm getting an index out of range error when running nofold_pipeline.py : 
I know that there are duplicate entries in my dataset; could this be the problem ? 

[...]
    Reading distance matrix file...
    Traceback (most recent call last):
      File "filter_clusters2.py", line 88, in <module>
        ci95 = things[-2]
    IndexError: list index out of range

**Comment by noncodo** [comment]
I think I didn't have my $PATH properly adjusted. This problem was resolved in a subsequent run.

**Comment by sarahmid** [comment]
Ok! Let me know if you have any other issues.
